### ISSUE TITLE
LDAC support

### ISSUE THREAD

**Issue by candiduslynx** [therealahrion/ViPER4Android-FX#11]
Double of https://github.com/therealahrion/ViPER4Android-FX/issues/9
Have the same issue (Processing: no) on my MI MIX 2 with RR + V4A installed either via TWRP or Magisk when codec is set to LDAC. WIth SBC everything works fine.

**Comment by candiduslynx** [comment]
Especially, it doesn't work with sample rate 96 kHz and 32 bit depth

**Comment by Zackptg5** [comment]
Unfortunately, that's something with the app itself and the latest version of the app (2.5.0.5) is closed source so it'd be best to take it up on the official thread: https://forum.xda-developers.com/showthread.php?t=2191223
This repo is more for the unity installer of v4a rather than the app itself. The actual repo for the app is here: https://github.com/vipersaudio/viper4android_fx (you'll see that the last updates were for 2.4 version of the app)

Between that thread, the thread for this mod, and the new unofficial v4a, there are quite a few questions about LDAC too:
Official app thread: https://forum.xda-developers.com/search/thread/2191223?query=ldac
Thread for this mod: https://forum.xda-developers.com/search/thread/3577058?query=ldac
Unofficial app thread: https://forum.xda-developers.com/search/thread/3774651?query=ldac

I don't use ldac myself so I won't be of much help there
