### ISSUE TITLE
Feature request: flip right and left channel

### ISSUE THREAD

**Issue by Jolanrensen** [therealahrion/ViPER4Android-FX#13]
I came across the issue where I was watching some YouTube video and the creator's left and right channel was flipped. It was mildly irritating as wearing in ear headphones with special left/right shape I couldn't just put the left one in my right ear and vice versa. Turns out there isn't a single app that can flip right and left audio. The only solution I found was to mirror the video so the sound would match... 

It's just a simple idea but I thought viper would be perfect for the job as you can already pan audio from left to right, why not be able to just flip it?

**Comment by Zackptg5** [comment]
Not a bad idea but we're not the app devs, we just made an installer that enables the app to work on lots of devices since the actual app hasn't been updated in a while. I suggest bringing it up on the unofficial 2.6 v4a thread on xda as those devs might be open to adding it in. The original viper Dev has been MIA for a while now
