### ISSUE TITLE
Doesn't work with LDAC codec enabled Google pixel 2 8.1

### ISSUE THREAD

**Issue by dviree** [therealahrion/ViPER4Android-FX#9]
It disables the processing when I enable the LDAC codec for my Sony mdr 1000
Idk if I should post a log because it's clearly a bug in the V4A

**Comment by Zackptg5** [comment]
Can you still pay a full local anyways? One after attempting to play music with ldac enabled and one with it disabled?
It does sound like a v4a app issue which there's nothing we can do about but it might not be

**Comment by dviree** [comment]
Yeah if I disable ldac it works no reboot required.
I'm 100% sure it's V4A. I sat with V4A for a whole day trying to get it to work. I thought maybe LDAC was the one blocking V4A and it was. It works 100% now
Cuz I tried first with my Sony mdr 1000 and it didn't work then I tried with another pair of aptx headphones and it worked. 
I can give you logs if you want

**Comment by Zackptg5** [comment]
Ya, could you send logs? If it is an app issues (which is what is sounds like), there's nothing I can do about it unfortunately

**Comment by Zackptg5** [comment]
Close due to inactivity

**Comment by eladcn** [comment]
I am having the exact same issue with Sony WH-1000xM2 and OnePlus 3T on Oreo.
It says "Processing: No" when the headphones are using LDAC codec and when I change them to SBC codec, V4A works perfectly fine.

It could be a problem with the codec itself, because Sony's app doesn't let you use their equalizer or any other kind of sound modification while using LDAC.

I can provide log files if needed (please tell me where the logs are located at).
